--liquibase formatted sql

--changeset posteq:1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    email      VARCHAR(50)                             UNIQUE NOT NULL,
    age        INTEGER                                 NOT NULL,
    created_at date                                    ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);